title: My Personal Blog
description: My Personal Blog
author: Daniel Czetner
github: https://github.com/moudlajs
about: I am working as tech. support guy at <a href="http://www.mergado.cz" target="_blank">MERGADO</a>
disqus_shortname: blogposts
google_analytics: UA-83600864-1

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/czetner"
    - icon: fa-skype
      link: "#"
    - icon: fa-twitter

share:
  twitter_username: 
  fb_appid:

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Github
      url: https://github.com/moudlajs
    - text: XML Feed
      url: /feed.xml
    
url: "https://danielczetner.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
